### ISSUE TITLE
ES6 Syntax used in exception

### ISSUE THREAD

**Issue by petermikitsh** [kevva/string-includes#1]
At [index.js:5](https://github.com/kevva/string-includes/blob/master/index.js#L5),

```js
		throw new TypeError(`Expected a \`string\`, got \`${typeof str}\``);
```

uses [ES6 Template Literals](https://github.com/addyosmani/es6-equivalents-in-es5#template-literals).

**Comment by arthurvr** [comment]
Since v2.0, this package only supports Node 4 and newer, those support template literals so it shouldn't be a problem. If you need support for older Node versions you could always use v1.

**Comment by petermikitsh** [comment]
Ah, for our particular use case, we were using this package in a browser environment and it was breaking in older browsers that don't support template literals, like IE 10.
